# Generated by Django 3.1.4 on 2021-10-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20211025_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prouser',
            new_name='user',
        ),
    ]
